---
- name: ensure nginx is installed
  apt: name=nginx update_cache=yes
- name: copy the nginx config
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
- name: copy the nginx default site config
  template: src=nginx-default.j2 dest=/etc/nginx/sites-available/default
- name: restart nginx
  service: name=nginx state=restarted