---
- name: Install PHP5 
  apt: name=php5 update_cache=yes
- name: install php5 extensions
  apt: name={{ item }} update_cache=yes
  with_items:
    - php5-curl
    - php5-gd
    - php5-imagick
    - php5-mysql
- name: config PHP
  action: ini_file dest=/etc/php5/apache2/php.ini section=PHP option=memory_limit value=64M mode=0600
  notify:
  - restart apache2
- name: config PHP
  action: ini_file dest=/etc/php5/apache2/php.ini section=PHP option=upload_max_filesize value=200M mode=0600
  notify:
  - restart apache2
- name: config PHP
  action: ini_file dest=/etc/php5/apache2/php.ini section=PHP option=post_max_size value=200M mode=0600
  notify:
  - restart apache2
- name: config PHP
  action: ini_file dest=/etc/php5/apache2/php.ini section=PHP option=allow_url_fopen value=Off mode=0600
  notify:
  - restart apache2
    